apiVersion: apps/v1
kind: Deployment
metadata:
  name: inaccurate-dataset-consumer-deployment
  labels:
    app: inaccurate-dataset-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inaccurate-dataset-consumer
  template:
    metadata:
      labels:
        app: inaccurate-dataset-consumer
    spec:
      containers:
      - name: inaccurate-dataset-consumer
        image: inchrist95/inaccurate_dataset_consumer_service:4.4
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "150m"
            memory: "384Mi"
