apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: label-service-hpa
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: label-server
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
      - type: Pods
        value: 3
        periodSeconds: 5
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
      - type: Pods
        value: 5
        periodSeconds: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    
