apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: label-service-hpa
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: label-server
  targetCPUUtilizationPercentage: 70
