apiVersion: apps/v1
kind: Deployment
metadata:
  name: parameter-consumer-deployment
  labels:
    app: parameter-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parameter-consumer
  template:
    metadata:
      labels:
        app: parameter-consumer
    spec:
      containers:
      - name: parameter-consumer
        image: 192.168.1.10:8443/parameter_consumer_service:4.7
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "150m"
            memory: "384Mi"
        volumeMounts:
        - name: nfs-vol
          mountPath: /usr/src/parameter
      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: nfs-pvc
